name: Update latest bus data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - env:
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
        run: |-
          npm ci
          npm run build-ci
      - run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          # git push
          # Set title and body for PR
          echo ::set-output name=pr_title::"Latest data: ${timestamp}"
          echo ::set-output name=pr_body::"$(node scripts/changes)"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: latest-data
          delete-branch: true
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
          labels: data
